services:
  todo-frontend:
    build:
      context: .
      dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
    ports:
      - 5005:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend
